version: '2.0'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/familiar
    ports:
      - "5000:5000"
    links:
      - db
  worker:
    build: .
    command: bundle exec rake jobs:work
    volumes:
      - .:/familiar
    links:
      - db
