version: '2.0'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - PORT=5000
      - RAILS_ENV=docker
    env_file: .env
    command: puma -C config/puma.rb
    volumes:
      - .:/familiar
    ports:
      - "5000:5000"
    links:
      - db
  worker:
    build: .
    environment: 
      - RAILS_ENV=docker
    env_file: .env
    command: rake jobs:work
    volumes:
      - .:/familiar
    tmpfs:
      - /tmp
    links:
      - db
